language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - jruby-19mode
  - rbx
before_script:
  - "cd rails_test"
  - "bundle install"
  - "rake db:setup RAILS_ENV=test"
script:
  - rspec
  - "export RAILS_VERSION=4.1.8; bundle update && rspec"
