language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
  - rbx
before_script:
  - "export DISPLAY=:99.0"
  - "cd rails_test"
  - "bundle install"
  - "rake db:setup RAILS_ENV=test"
script: rspec